language: python
python:
  - "3.6"

install: pip install pycodestyle pylint pylint-quotes pyyaml

script:
  - pylint --load-plugins pylint_quotes generators
  - pycodestyle --config=.pycodestyle .
  - bash ./scripts/generate_all.sh cpp_builder
  - bash ./scripts/generate_all.sh java
  - bash ./scripts/generate_all.sh typescript
